GOOGLE_API_KEY_ENV = 'GOOGLE_API_KEY'
GOOGLE_API_CX_ENV = 'GOOGLE_API_CX'
OPENAI_KEY_ENV = 'OPENAI_KEY'

REQUIRED_ENV = [GOOGLE_API_KEY_ENV,
                GOOGLE_API_CX_ENV,
                OPENAI_KEY_ENV]

MAX_PROMPT_LENGTH = 8192  # unsure, but approx 2048x4
